### ISSUE TITLE
createContainer command fails with a syntax error

### ISSUE THREAD

**Issue by manikjain** [Azure-Samples/storage-blobs-node-quickstart#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone the repo.
> Create a .env file and add the connection string.
> Run `npm install`.
> Run `node index.js --command createContainer`.

### Any log messages given by the failure
>

```
[mjain] ~/Documents/nodejs/storage-blobs-node-quickstart$ node index.js --command createContainer
/Users/manik.jain/Documents/nodejs/storage-blobs-node-quickstart/index.js:90
const executeCommand = async () => {
                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

### Expected/desired behavior
> Create a container or post a success message.

### OS and Version?
> macOS High Sierra

### Versions
> node version: `v6.11.2`

### Mention any other details that might be useful
> Following the doc here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-nodejs

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by manikjain** [comment]
It worked fine after upgrading node to version `v8.11.2`. It seems like node might not have added support for default async until v7~ onwards.
